### ISSUE TITLE
Add Home Brew Cask Support

### ISSUE THREAD

**Issue by jinxuan** [klauscfhq/ao#17]
Hi, Could you please consider add [homebrew cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) installation support?

**Comment by klauscfhq** [comment]
I was hoping that someone from the community would take this up. If anyone is interested in giving it a try, a [readme](https://github.com/klauscfhq/ao/blob/master/readme.md#install) Pull Request would be super welcome : )

**Comment by jinxuan** [comment]
I have a create a pull request for this.
