### ISSUE TITLE
Hacktoberfest: Create a Black Theme

### ISSUE THREAD

**Issue by klauscfhq** [klauscfhq/ao#2]
Hi there! : )
Celebrating the Hacktoberfest festivities, everyone is welcome to build a black theme for Ao. It should be a simple clone of the `style/dark-mode.css` with the only differences the **css theme selector** and the **color variables**, where:

- `html.dark-mode` should become `html.black-mode`
- `var(--dark-grey)` should give its place to `var(--black)`
- `var(--grey)` should give its place to `var(--light-black)`

Happy Hacktoberfest and happy hacking! 🎉

**Comment by andrey-semin** [comment]
I can take this :-)

**Comment by klauscfhq** [comment]
@andrey-semin I am so sorry but that one has already been assigned. If you feel like it, you are more than welcome to give a try to this one right [here](https://github.com/champloohq/hyper-pokemon/issues/24) instead. Happy hacking : )

**Comment by andrey-semin** [comment]
there is a guy requesting for it already so it seems like i'm late to the party :-)

**Comment by klauscfhq** [comment]
@andrey-semin You can take this one if you would like to https://github.com/champloohq/tusk/issues/24
