### ISSUE TITLE
App won't start - "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by jaredreich** [klauscfhq/ao#20]
## Repro steps

Download .dmg from release, mount, drag AO to applications folder, open AO app

### Error Message

![image](https://user-images.githubusercontent.com/8563847/38912736-38143356-4294-11e8-8662-c3e4881614b2.png)

## Environment

macOS 10.13.2

**Comment by klauscfhq** [comment]
Thank you for taking the time to report the issue : )
