### ISSUE TITLE
Hacktoberfest: Update Dependencies

### ISSUE THREAD

**Issue by klauscfhq** [klauscfhq/ao#4]
Hi there! : )
To celebrate the Hacktoberfest festivities, everyone is welcome to update the following group of `dependencies` to their latest versions. It should be really simple and easy. Here are the links to the packages on `npmjs.com`, you can find their latest version on the right side of the page:

- [`ms`](https://www.npmjs.com/package/ms)
- [`fs-extra`](https://www.npmjs.com/package/fs-extra)
- [`simple-get`](https://www.npmjs.com/package/simple-get)

Happy Hacktoberfest and happy hacking! 🎉

**Comment by johnsylvain** [comment]
I'll take this one
