### ISSUE TITLE
Transparent status bar with vibrant themes

### ISSUE THREAD

**Issue by Riccorl** [klauscfhq/ao#9]
## Description

When vibrant themes are chosen I get a transparent status bar. 
A screenshot:
![image](https://user-images.githubusercontent.com/10062216/32346631-363c4644-c00e-11e7-812b-f017dd5dcdf4.png)

## Environment

Latest version, so 5.0.0, on MacBook Pro with macOS 10.13.1 and an iMac with macOS 10.13.0

OS Type:        Darwin
OS Platform:    darwin
OS Release:     17.2.0
Architecture:   x64

**Comment by klauscfhq** [comment]
Thanks for taking the time to report it : )
